apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "jenkins-test-cred"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
    "jenkins.io/credentials-scope": "global"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: YWRtaW4=
  password: bXlzZWNyZXRwYXNzd29yZA==
